# -*- coding: utf-8 -*-
"""Air_Quality_Hypothesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gw6r0JM5sPdHgXHdYF_gHWKfl1abDlF6
"""

# STEP 1: Import libraries
import pandas as pd
from scipy import stats

# STEP 2: Loading data from Excel
file_path = 'Air_Quality_EDA_Vamshi_Aitharaju_Final.xlsx'
data = pd.read_excel(file_path, sheet_name='Hypothesis Testing')

# STEP 3: Get each column of data
winter_pm25 = data['Winter PM2.5'].dropna()
summer_pm25 = data['Summer PM2.5'].dropna()
winter_no2 = data['Winter NO2'].dropna()
summer_no2 = data['Summer NO2'].dropna()
annual_pm25 = data['Annual PM2.5'].dropna()
annual_no2 = data['Annual NO2'].dropna()
# dropna() removes empty cells (like filtering out blanks in Excel)

print("AIR QUALITY HYPOTHESIS TESTING RESULTS")

# TEST 1: Is Winter PM2.5 different from Summer PM2.5?
print("\nTEST 1: Winter PM2.5 vs Summer PM2.5")

# Calculate averages (like using AVERAGE() in Excel)
winter_pm25_avg = winter_pm25.mean()
summer_pm25_avg = summer_pm25.mean()

print(f"Winter PM2.5 average = {winter_pm25_avg:.2f}")
print(f"Summer PM2.5 average = {summer_pm25_avg:.2f}")
print(f"Difference = {winter_pm25_avg - summer_pm25_avg:.2f}")

# Do the t-test (like using Excel's T.TEST function)
# This compares two independent groups
t_stat_1, p_value_1 = stats.ttest_ind(winter_pm25, summer_pm25)

print(f"\n p-value = {p_value_1:.6f}")

# Interpretation (Is the difference real or just random?)
if p_value_1 < 0.05:
    print("SIGNIFICANT - Winter and Summer PM2.5 ARE different!")
else:
    print("NOT SIGNIFICANT - No real difference found")

# TEST 2: Is Winter NO2 different from Summer NO2?
print("\nTEST 2: Winter NO2 vs Summer NO2")

# Calculate averages
winter_no2_avg = winter_no2.mean()
summer_no2_avg = summer_no2.mean()

print(f"Winter NO2 average = {winter_no2_avg:.2f}")
print(f"Summer NO2 average = {summer_no2_avg:.2f}")
print(f"Difference = {winter_no2_avg - summer_no2_avg:.2f}")

# Do the t-test
t_stat_2, p_value_2 = stats.ttest_ind(winter_no2, summer_no2)

print(f"\n p-value = {p_value_2:.6f}")

# Interpretation
if p_value_2 < 0.05:
    print("SIGNIFICANT - Winter and Summer NO2 ARE different!")
else:
    print("NOT SIGNIFICANT - No real difference found")

# TEST 3: Is Annual PM2.5 different from Annual NO2?
print("\nTEST 3: Annual PM2.5 vs Annual NO2")


# Calculate averages
annual_pm25_avg = annual_pm25.mean()
annual_no2_avg = annual_no2.mean()

print(f"Annual PM2.5 average = {annual_pm25_avg:.2f}")
print(f"Annual NO2 average = {annual_no2_avg:.2f}")
print(f"Difference = {annual_pm25_avg - annual_no2_avg:.2f}")

# Do the PAIRED t-test (because we're comparing same locations/times)
t_stat_3, p_value_3 = stats.ttest_rel(annual_pm25, annual_no2)

print(f"\n p-value = {p_value_3:.6f}")

# Interpretation
if p_value_3 < 0.05:
    print("SIGNIFICANT - PM2.5 and NO2 ARE different!")
else:
    print("NOT SIGNIFICANT - No real difference found")

#FINAL SUMMARY TABLE
print("SUMMARY")
print(f"  Test 1 (Winter vs Summer PM2.5): {'SIGNIFICANT' if p_value_1 < 0.05 else 'NOT SIGNIFICANT'}")
print(f"  Test 2 (Winter vs Summer NO2): {'SIGNIFICANT' if p_value_2 < 0.05 else 'NOT SIGNIFICANT'}")
print(f"  Test 3 (Annual PM2.5 vs NO2): {'SIGNIFICANT' if p_value_3 < 0.05 else 'NOT SIGNIFICANT'}")