# -*- coding: utf-8 -*-
"""Air_Quality_Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FJuA_Qj4Npx4CIyhX8NgXTbhCIne74ua
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.holtwinters import ExponentialSmoothing

# PART 1: Settings (Change these if professor asks)
excel_file = 'Air_Quality_Prepared.xlsx'  # Your Excel file
forecast_years = 4                         # How many years to predict
alpha = 0.50                               # Weight for recent data
beta = 0.25                                # Weight for trend

# PART 2: Function to Make Predictions
def make_prediction(sheet_name):
    """This function reads data and makes predictions"""

    # Step 1: Read Excel file
    df = pd.read_excel(excel_file, sheet_name=sheet_name)

    # Step 2: Clean the data
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.groupby('Date')['Value'].mean().reset_index()
    df = df.sort_values('Date')

    # Step 3: Find the last date in your data
    last_date = df['Date'].max()

    # Step 4: Create future dates (2024, 2025, 2026, 2027)
    future_dates = pd.date_range(
        start=last_date + pd.DateOffset(years=1),
        periods=forecast_years,
        freq='YS'
    )

    # Step 5: Create the prediction model
    model = ExponentialSmoothing(
        df['Value'],
        trend='add',
        seasonal=None
    )

    # Step 6: Train the model with your alpha and beta
    trained = model.fit(
        smoothing_level=alpha,
        smoothing_trend=beta,
        optimized=False
    )

    # Step 7: Get predictions for future years
    predictions = trained.forecast(steps=forecast_years)

    # Step 8: Calculate confidence range (how sure we are)
    error = np.std(trained.resid)
    lower_range = []
    upper_range = []
    for i in range(forecast_years):
        margin = 1.96 * error * np.sqrt(i + 1)
        lower_range.append(predictions.iloc[i] - margin)
        upper_range.append(predictions.iloc[i] + margin)

    # Step 9: Show results on screen
    print(f"\n{sheet_name} Predictions:")
    print("-" * 50)
    for i in range(forecast_years):
        year = future_dates[i].year
        value = predictions.iloc[i]
        lower = lower_range[i]
        upper = upper_range[i]
        print(f"  {year}: {value:.2f} (between {lower:.2f} and {upper:.2f})")

    # Step 10: Return all data for charting
    return {
        'historical_dates': df['Date'].tolist(),
        'historical_values': df['Value'].tolist(),
        'forecast_dates': future_dates.tolist(),
        'forecast_values': predictions.tolist(),
        'lower_confidence': lower_range,
        'upper_confidence': upper_range
    }

# PART 3: Function to Draw Charts
def draw_chart(data, title):
    """This function creates a visual chart"""

    # Create blank chart
    fig, ax = plt.subplots(figsize=(14, 7))

    # Draw past data (blue line)
    ax.plot(
        data['historical_dates'],
        data['historical_values'],
        color='#5B9BD5',
        linewidth=2,
        marker='o',
        markersize=4,
        label='Historical Data'
    )

    # Draw connecting line between past and future
    ax.plot(
        [data['historical_dates'][-1], data['forecast_dates'][0]],
        [data['historical_values'][-1], data['forecast_values'][0]],
        color='#ED7D31',
        linewidth=2,
        alpha=0.5
    )

    # Draw predictions (orange line)
    ax.plot(
        data['forecast_dates'],
        data['forecast_values'],
        color='#ED7D31',
        linewidth=2,
        marker='o',
        markersize=4,
        label='Forecast'
    )

    # Draw shaded confidence area
    ax.fill_between(
        data['forecast_dates'],
        data['lower_confidence'],
        data['upper_confidence'],
        color='#ED7D31',
        alpha=0.2,
        label='95% Confidence Range'
    )

    # Add labels and title
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.set_xlabel('Year', fontsize=11)
    ax.set_ylabel('Value', fontsize=11)
    ax.legend(loc='best')
    ax.grid(True, alpha=0.3)

    # Format x-axis to show years clearly
    all_dates = data['historical_dates'] + data['forecast_dates']
    years = sorted(set([pd.to_datetime(d).year for d in all_dates]))
    year_positions = [pd.Timestamp(year=y, month=1, day=1) for y in years]
    ax.set_xticks(year_positions)
    ax.set_xticklabels(years, rotation=45)

    plt.tight_layout()
    plt.show()

# PART 4: Run the Program
print("Starting Air Quality Forecasting")
print(f"Settings: {forecast_years} years | Alpha={alpha} | Beta={beta}")

# List of all sheets in your Excel file
all_sheets = [
    'Annual_NO2',
    'Annual_PM25',
    'Winter_NO2',
    'Summer_NO2',
    'Combined_PM25'
]

# Process each sheet one by one
for sheet in all_sheets:
    # Make predictions
    result = make_prediction(sheet)

    # Draw chart
    chart_title = sheet.replace('_', ' ') + ' - Forecast to 2027'
    draw_chart(result, chart_title)